import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <head>
        <title>سفر نگار</title>
        <meta name="description" content="در این وب‌سایت خاطرات و تجربیات من از سفر به جاهای دیدنی ایران و دیگر مقاصد گردشگری را بخوانید." />
        <meta name="keywords" content="گزارش سفر
،سفرنامه، سفر به کرمانشاه, گردشگری ایران, سفر به گیلان, سفرهای خاطره‌انگیز"  />
        <link rel="icon" href="/favicon.ico" sizes="any"></link>
      </head>
      <body className="font-sans bg-gray-100 text-gray-800">
        {/* هدر */}
        <header className="bg-blue-500 text-white p-4 text-center">
          <Navbar/>
        </header>

        {/* محتوای صفحات */}
        <main className="max-w-2xl mx-auto p-6">
          {children}
        </main>

        {/* فوتر */}
        <footer className="bg-blue-500 text-white p-4 text-center">
          <p>© 2025 سفر نگار - تمامی حقوق محفوظ است</p>
        </footer>
      </body>
    </html>
  );
}
